build:
    dependencies:
        before:
            - rm requirements.txt
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                before:
                    - export NUMBA_DISABLE_JIT=1
                override: [py-scrutinizer-run]
            
filter:
    excluded_paths:
        - tests/*
        - compare/pdi_comparison.py
        - misc/*
        - requirements.txt
        
checks:
    python:
        code_rating: true
        duplicate_code: true
