build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                before:
                    - export NUMBA_DISABLE_JIT=1
                override:
                    - pip install -r requirements.txt
                    - python -W ignore -m unittest tests/test_*.py
filter:
    excluded_paths:
        - example_inputs/*
        - scripts/compare/*
        - scripts/ingest/*
        - scripts/process/*
        - scripts/task/*
        - misc/*
        - notebooks/*
        - tests/*
        
checks:
    python:
        code_rating: true
        duplicate_code: true
