build:
    nodes:
        analysis:
            project_setup:
                override: true
            tests:
                before:
                    - export NUMBA_DISABLE_JIT=1
                override: [py-scrutinizer-run]
    tests:
        before:
            - export NUMBA_DISABLE_JIT=1
        override: [py-scrutinizer-run]
            coverage:
                file: '.coverage'
                config_file: '.coveragerc'
                format: 'py-cc'       
filter:
    excluded_paths:
        - compare/*
        - example_inputs/*
        - ingest/*
        - misc/*
        - notebooks/*
        - process/*
        - tests/*
        
checks:
    python:
        code_rating: true
        duplicate_code: true
