language: python

python:
    - 3.5
    - 3.6

install: 
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n test-environment -f dependencies.txt
  - source activate test-environment
  - python setup.py install

script: nosetests
#  - cd tests
#  - python -m unittest test_*.py
