language: python

python:
  - 3.6

install: 
  # download latest miniconda
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # create an environment named 'indices_python', activate it, and add the package via PIP 
  - conda create -n indices_python
  - source activate indices_python
  - pip install .

script: 
  # run all tests with coverage 
  - export NUMBA_DISABLE_JIT=1  # disable numba JIT
  - coverage run --source=indices_python setup.py test
  
after_success:
  # get a code coverage report for coveralls.io integration
  - coveralls

# don't email after every build success/failure (default behavior)
notifications:
  email: false
